#!/bin/bash

FILE='pokemon_data/bulbasaur.json'

# Extract with jq
name=$(jq -r '.name' "$FILE" | sed 's/.*/\u&/')
formatted_height=$(jq '.height' "$FILE" | awk '{printf "%.1f", $1/10}')
formatted_weight=$(jq '.weight' "$FILE" | awk '{printf "%.1f", $1/10}')
type=$(jq -r '.types[0].type.name' "$FILE" | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."